language:
  - java

os:
  - linux

jdk:
  - oraclejdk8

# goto build dubbox
# goto build metaq
before_install:
  - git clone https://github.com/dangdangdotcom/dubbox.git
  - cd dubbox
  - mvn clean install -Dmaven.test.skip
  - cd ..
  - git clone https://github.com/killme2008/Metamorphosis.git
  - cd Metamorphosis
  - mvn clean install -Dmaven.test.skip
  - cd ..

install:
  - mvn clean install

notifications:
  email:
    - zhang_yao_wu1993@yeah.net
